"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  English: {
    // Navbar
    nav_dashboard: "Dashboard",
    nav_profile: "My Profile",
    nav_login: "Sign In",
    nav_logout: "Log Out",
    nav_select_lang: "Language",
    nav_home: "Home",
    nav_theme_light: "Light Mode",
    nav_theme_dark: "Dark Mode",
    nav_pricing: "Pricing",
    nav_get_started: "Get Started",
    nav_online: "Online",
    nav_current_plan: "Current Plan",
    nav_upgrade_btn: "Upgrade",
    nav_manage_account: "Manage Account",
    nav_analytics_view: "Analytics View",
    nav_view_tiers: "View Tiers",
    nav_secure_signout: "Secure Sign Out",
    nav_sync_active: "Settings Sync Active",
    // Home Page
    hero_badge: "AI BUSINESS TOOLS",
    hero_title_1: "Create Your",
    hero_title_2: "Success Plan",
    hero_subtitle: "Find the best business ideas in your city using real-time local data and AI analysis.",
    btn_start_scan: "Search for Ideas",
    btn_pricing: "View Plans",
    home_nav_features: "How it Works",
    home_nav_plan: "Plan",
    home_nav_stories: "Stories",
    home_feat_badge: "SMART TOOLS",
    home_feat_title_1: "Tools for",
    home_feat_title_2: "Success",
    home_feat_desc: "We provide everything you need to find, plan, and launch a successful local business.",
    home_feat_1_title: "Global Data",
    home_feat_1_desc: "Live market data from cities around the world.",
    home_feat_2_title: "AI Analysis",
    home_feat_2_desc: "Smart insights on the best business gaps.",
    home_feat_3_title: "6-Month Roadmap",
    home_feat_3_desc: "A clear step-by-step path to growth.",
    home_feat_4_title: "Competitor Analysis",
    home_feat_4_desc: "See who else is in your market and how to win.",
    home_feat_5_title: "Profit Forecast",
    home_feat_5_desc: "Estimated income based on local demand.",
    home_feat_6_title: "Real-time Alerts",
    home_feat_6_desc: "Stay updated on new market trends.",
    home_story_badge: "USER STORIES",
    home_story_title_1: "Trusted by Many",
    home_story_title_2: "Worldwide",
    home_story_1_quote: "StarterScope helped me find the best spot for my food truck. My income tripled!",
    home_story_1_role: "Food Truck Owner",
    home_story_2_quote: "The AI analysis was perfect. I found a great market and got clients quickly.",
    home_story_2_role: "Consultant",
    home_story_3_quote: "I found a business gap that nobody saw. My studio is now fully booked!",
    home_story_3_role: "Studio Founder",
    home_story_revenue_label: "Monthly Income",
    feat_title: "How It Works",
    feat_subtitle: "We analyze local searches and trends to show you exactly what's missing in your market.",
    feat_1_title: "Pick a Location",
    feat_1_desc: "Search any city to see what people are looking for.",
    feat_2_title: "Check Profits",
    feat_2_desc: "Our AI helps you see which ideas are most likely to make money.",
    feat_3_title: "Step-by-Step Guide",
    feat_3_desc: "Get a clear plan from your first day to full growth.",
    banner_title: "Start Your Business Today",
    banner_desc: "Join thousands of founders using data to build better businesses.",
    banner_btn: "Get Started",
    // Dashboard
    dash_market_scope: "Location Search",
    dash_target_loc: "City or Region",
    dash_enter_city: "Type a city name...",
    dash_analyze: "Search Now",
    dash_analyze_btn: "Analyze Market",
    dash_analyzing: "Searching...",
    dash_ai_insights: "AI Market Report",
    dash_ai_desc: "Enter a city to see the best business opportunities. We analyze local trends and competition for you.",
    dash_vector_global: "Market Trends",
    dash_vector_predict: "Profit Forecasts",
    dash_results_header: "Results:",
    dash_strategic_opps: "Business Ideas",
    dash_view_plan: "See 6-Month Plan",
    dash_match_score: "Success Rate",
    dash_revenue: "Monthly Income",
    dash_capital: "Starting Cost",
    dash_prob: "Chance of Success",
    dash_neural_input: "Data Sources",
    dash_source_web: "Google Trends",
    dash_source_reddit: "Reddit Feedback",
    dash_empty_title: "Ready to Start",
    dash_empty_desc: "Enter a location on the left to see the best business ideas for that area.",
    dash_limit_reached: "Limit Reached",
    dash_limit_desc: "Search limit reached for your plan.",
    dash_upgrade_now: "Upgrade Now",
    dash_recent_searches: "Recent Searches",
    dash_history_desc: "Your search history",
    dash_refresh: "Refresh",
    dash_use_current_loc: "Use current location",
    // Roadmap
    road_return: "Back to Dashboard",
    road_implement_guide: "Implementation Guide",
    road_directive: "Business Plan",
    road_milestones: "Launch Steps",
    road_timeline: "Timeline",
    road_team: "Items Needed",
    road_phase: "STEP",
    road_priority: "High Priority",
    road_action: "Action Needed",
    road_readiness: "Plan Ready",
    road_confirmed_desc: "Your step-by-step plan is ready. You can begin now.",
    road_print: "Download PDF",
    road_preparing: "Preparing Plan",
    road_analyzing: "Analyzing Market...",
    road_strategy: "Strategy",
    road_plan_title: "Your Growth Plan",
    road_success_conf: "Analysis complete. Good chance of success!",
    road_fast_growth: "Quick Growth",
    road_fast_desc: "Use AI to find customers faster and grow your business.",
    road_market_safety: "Market Safety",
    road_safety_desc: "Use local data to stay safe during market changes.",
    road_6_months: "6 Months Plan",
    road_taskforce: "Required Tools",
    road_expert_exec: "Execution Tips",
    road_tip_1: "Automate core tasks",
    road_tip_2: "Build local presence",
    road_tip_3: "Launch quickly",
    road_strategies: "Growth Strategies",
    road_loading_strat: "Loading Strategy...",
    // Profile
    prof_header: "Profile Settings",
    prof_email_label: "Email",
    prof_name: "Full Name",
    prof_bio: "Short Bio",
    prof_phone: "Phone Number",
    prof_company: "Company",
    prof_company_name: "Company Name",
    prof_location: "Location",
    prof_location_found: "Location Found",
    prof_deploy_location: "Use This Location",
    prof_website: "Website",
    prof_industry: "Industry",
    prof_select_sector: "Choose Industry",
    prof_save: "Save Changes",
    prof_saving: "Saving Changes...",
    prof_updated: "Profile saved!",
    prof_placeholder_name: "Enter full name",
    prof_placeholder_bio: "Tell us about your goals...",
    prof_placeholder_phone: "Enter phone number",
    prof_placeholder_company: "Business name",
    prof_placeholder_location: "City, Country",
    prof_placeholder_website: "https://example.com",
    prof_placeholder_industry: "Select your sector",
    prof_loading: "Loading profile...",
    // Pricing
    price_title: "Pricing Plans",
    price_subtitle: "Choose the best plan to unlock your next business opportunity.",
    price_explorer: "Explorer (Free)",
    price_explorer_desc: "Perfect for students & beginners to explore ideas.",
    price_starter: "Starter",
    price_starter_desc: "Convert ideas into action with city-level insights.",
    price_pro: "Professional (Pro)",
    price_pro_desc: "The serious choice for entrepreneurs & founders.",
    price_growth: "Growth Business",
    price_growth_desc: "Bridge the gap with small business analytics.",
    price_enterprise: "Enterprise Dominance",
    price_enterprise_desc: "High-ticket solutions for agencies & companies.",
    price_feat_heatmap: "Competitor Heatmaps",
    price_feat_custom_search: "Custom AI Search",
    price_feat_review_score: "Review Scoring",
    price_feat_prediction: "Trend Prediction",
    price_feat_segment: "Customer Segments",
    price_feat_forecast: "Revenue Forecasting",
    price_feat_team: "Team Access (2-5)",
    price_feat_crm: "CRM Integration",
    price_feat_white_label: "White-label Solution",
    price_feat_api_lite: "Limited API Access",
    price_feat_api_full: "Full API & Custom Models",
    price_monthly: "Monthly",
    price_yearly: "Yearly",
    price_annually: "Annually",
    price_bill_monthly: "Monthly Billing",
    price_bill_yearly: "Yearly Billing",
    price_bill_annually: "Bill Annually",
    price_most_popular: "Most Popular",
    price_save: "SAVE 20%",
    price_custom: "Custom Plan",
    price_contact: "Contact Sales",
    price_upgrade: "Upgrade Now",
    price_free: "Get Started Free",
    price_feat_support: "Priority Support",
    price_feat_api: "API Access",
    price_feat_multi: "Multi-Region",
    price_stat_capital: "Capital Invested",
    price_stat_market: "Market Accuracy",
    price_stat_precision: "Reliability",
    price_trusted: "Trusted by Many",
    price_partnerships: "Successful Projects",
    dash_mentors: "Similar Businesses",
    dash_mentor_desc: "See existing businesses in this sector for better insights.",
    dash_connect: "Analyze",
    // Footer & Generic
    foot_desc: "Smart Business Intelligence. Helping you build better businesses with AI.",
    foot_status: "Systems: All Good",
    foot_strategic: "Explore",
    foot_legal: "Legal",
    foot_scan: "Market Search",
    foot_regional: "Local Insights",
    foot_privacy: "Privacy",
    foot_terms: "Terms",
    foot_compliance: "Compliance",
    foot_contact: "Contact Us",
    foot_all_rights: "All Rights Reserved",
    foot_stable: "Singularity v6.4.2",
    go_back: "Go Back",
    // Auth
    auth_welcome: "Sign In",
    auth_join: "Create Account",
    auth_login_desc: "Log in to see your growth plan.",
    auth_signup_desc: "Sign up to start searching for ideas.",
    auth_signin_tab: "Sign In",
    auth_signup_tab: "Sign Up",
    auth_name: "Full Name",
    auth_email: "Email Address",
    auth_pass: "Password",
    auth_confirm: "Confirm Password",
    auth_btn_login: "Sign In",
    auth_btn_signup: "Create Account",
    auth_or: "Or continue with",
    auth_google: "Continue with Google",
    auth_footer_1: "Start Your Business Journey Today.",
    auth_footer_desc: "Our AI finds the best business ideas for you.",
    auth_feat_1: "Smart Market Analysis",
    auth_feat_2: "Check Competitors",
    auth_feat_3: "Instant Market Alerts",
    auth_feat_4: "Business Reports",
    auth_init: "Starting...",
    // Contact
    contact_title: "Help & Support",
    contact_subtitle: "Have questions? Our team is here to help you 24/7.",
    contact_mail_title: "Email Us",
    contact_mail_sub: "Typical response: 2 hours",
    contact_loc_title: "Our Office",
    contact_loc_sub: "Silicon Valley, CA",
    contact_support_title: "Live Support",
    contact_support_sub: "Available for Pro users",
    contact_form_name: "Your Name",
    contact_form_email: "Your Email",
    contact_form_subject: "Subject",
    contact_form_message: "Message",
    contact_form_btn: "Send Message",
    contact_success: "Thank you! We'll get back to you soon.",
    contact_id_self: "Tell us who you are...",
    contact_obj: "What do you need?",
    contact_msg_dir: "Your message...",
    contact_transmit: "Send Now",
    // Privacy, Terms, Compliance
    priv_title: "Privacy Policy",
    priv_section_1: "1. Information We Collect",
    priv_content_1: "We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.",
    priv_section_2: "2. How We Use Information",
    priv_content_2: "We use the information to provide, maintain, and improve our services, process transactions, and communicate with you.",
    priv_section_3: "3. Information Sharing",
    priv_content_3: "We do not sell or trade your personal information to third parties without your consent.",
    priv_section_4: "4. Data Security",
    priv_content_4: "We implement security measures to protect your personal information against unauthorized access.",
    priv_section_5: "5. Contact Us",
    priv_content_5: "If you have questions about this policy, please contact us at",
    terms_title: "Terms of Service",
    terms_section_1: "1. Acceptance of Terms",
    terms_content_1: "By accessing StarterScope, you agree to follow these Terms of Service and all laws.",
    terms_section_2: "2. User Accounts",
    terms_content_2: "You are responsible for keeping your account secure and for all actions under your account.",
    terms_section_3: "3. Service Usage",
    terms_content_3: "Our service is for business analysis. Do not use it for any illegal activities.",
    terms_section_4: "4. Payments",
    terms_content_4: "All payments are processed securely. Subscriptions can be canceled at any time.",
    terms_section_5: "5. Changes",
    terms_content_5: "We may update these terms. Continued use means you accept the new terms.",
    comp_title: "Compliance & Security",
    comp_subtitle: "We follow global standards to keep your business data safe.",
    comp_section_1: "Data Protection (GDPR)",
    comp_content_1: "We follow GDPR rules for all users, ensuring your right to data access and deletion.",
    comp_section_2: "Secure Payments",
    comp_content_2: "All transactions are encrypted and follow PCI-DSS standards for security.",
    comp_section_3: "System Availability",
    comp_content_3: "Our systems are monitored 24/7 to ensure 99.9% uptime for your business.",
    comp_section_4: "Audit Logs",
    comp_content_4: "We keep secure logs of all major system actions to prevent unauthorized access."
  },
  Hindi: {
    // Navbar
    nav_dashboard: "डैशबोर्ड",
    nav_profile: "मेरी प्रोफ़ाइल",
    nav_login: "साइन इन",
    nav_logout: "लॉग आउट",
    nav_select_lang: "भाषा",
    nav_home: "होम",
    nav_theme_light: "लाइट मोड",
    nav_theme_dark: "डार्क मोड",
    nav_pricing: "प्राइसिंग",
    nav_get_started: "शुरू करें",
    nav_online: "ऑनलाइन",
    nav_current_plan: "वर्तमान प्लान",
    nav_upgrade_btn: "अपग्रेड",
    nav_manage_account: "अकाउंट मैनेज",
    nav_analytics_view: "एनालिटिक्स व्यू",
    nav_view_tiers: "प्लान देखें",
    nav_secure_signout: "सुरक्षित लॉगआउट",
    nav_sync_active: "सेटिंग्स सिंक चालू",
    // Home Page
    hero_badge: "स्मार्ट बिज़नेस AI",
    hero_title_1: "अपना सफल",
    hero_title_2: "बिज़नेस प्लान करें",
    hero_subtitle: "शहर में सबसे पहले बिज़नेस के अच्छे मौके ढूँढने के लिए हमारे AI का उपयोग करें।",
    btn_start_scan: "आइडिया सर्च करें",
    btn_pricing: "प्लान देखें",
    home_nav_features: "यह कैसे काम करता है",
    home_nav_plan: "बिज़नेस प्लान",
    home_nav_stories: "कहानियां",
    home_feat_badge: "स्मार्ट टूल्स",
    home_feat_title_1: "सफलता के लिए",
    home_feat_title_2: "सही टूल्स",
    home_feat_desc: "हम आपको सफल लोकल बिज़नेस शुरू करने के लिए ज़रूरी हर चीज़ देते हैं।",
    home_feat_1_title: "ग्लोबल डेटा",
    home_feat_1_desc: "दुनिया भर के शहरों का लाइव मार्केट डेटा।",
    home_feat_2_title: "AI एनालिसिस",
    home_feat_2_desc: "बिज़नेस के अच्छे मौकों पर स्मार्ट जानकारी।",
    home_feat_3_title: "6 महीने का प्लान",
    home_feat_3_desc: "तरक्की के लिए एक साफ़ स्टेप-बाय-स्टेप रास्ता।",
    home_feat_4_title: "कम्पटीशन की पकड़",
    home_feat_4_desc: "देखें कि आपके मार्केट में कौन है और कैसे जीतें।",
    home_feat_5_title: "फायदे का अनुमान",
    home_feat_5_desc: "लोकल डिमांड के आधार पर संभावित कमाई।",
    home_feat_6_title: "ताज़ा अपडेट",
    home_feat_6_desc: "मार्केट के नए ट्रेंड्स की जानकारी रखें।",
    home_story_badge: "यूजर की कहानियां",
    home_story_title_1: "हज़ारों का भरोसा",
    home_story_title_2: "पूरी दुनिया में",
    home_story_1_quote: "StarterScope ने मेरे फ़ूड ट्रक के लिए सबसे अच्छी जगह ढूँढने में मदद की। मेरी कमाई तीन गुना बढ़ गई!",
    home_story_1_role: "फ़ूड ट्रक मालिक",
    home_story_2_quote: "AI एनालिसिस एकदम सही था। मुझे अच्छा मार्केट मिला और क्लाइंट्स जल्दी जुड़ गए।",
    home_story_2_role: "कंसल्टेंट",
    home_story_3_quote: "मुझे ऐसा बिज़नेस गैप मिला जो किसी ने नहीं देखा था। मेरा स्टूडियो अब पूरी तरह बुक रहता है!",
    home_story_3_role: "स्टूडियो फाउंडर",
    home_story_revenue_label: "मंथली कमाई",
    feat_title: "यह कैसे काम करता है",
    feat_subtitle: "हम लोकल सर्च और ट्रेंड्स को समझते हैं ताकि आपको सही रास्ता दिखा सकें।",
    feat_1_title: "लोकेशन चुनें",
    feat_1_desc: "किसी भी शहर में देखें कि लोग क्या ढूँढ रहे हैं।",
    feat_2_title: "मुनाफा देखें",
    feat_2_desc: "हमारा AI बताता है कि किस काम में ज़्यादा फायदा है।",
    feat_3_title: "स्टेप-बाय-स्टेप गाइड",
    feat_3_desc: "शुरुआत से लेकर कामयाबी तक का साफ़ रास्ता पाएं।",
    banner_title: "आज ही अपना बिज़नेस शुरू करें",
    banner_desc: "हज़ारों उद्यमियों के साथ जुड़ें जो डेटा की मदद से बिज़नेस बना रहे हैं।",
    banner_btn: "शुरू करें",
    // Dashboard
    dash_market_scope: "लोकेशन सर्च",
    dash_target_loc: "शहर या क्षेत्र",
    dash_enter_city: "शहर का नाम लिखें...",
    dash_analyze: "अभी सर्च करें",
    dash_analyze_btn: "एनालिसिस करें",
    dash_analyzing: "सर्च किया जा रहा है...",
    dash_ai_insights: "AI मार्केट रिपोर्ट",
    dash_ai_desc: "बेहतरीन मौकों को देखने के लिए शहर चुनें। हम आपके लिए लोकल ट्रेंड्स और कम्पटीशन को समझते हैं।",
    dash_vector_global: "मार्केट ट्रेंड्स",
    dash_vector_predict: "फायदे का अनुमान",
    dash_results_header: "नतीजे:",
    dash_strategic_opps: "बिज़नेस आइडिया",
    dash_view_plan: "6 महीने का प्लान देखें",
    dash_match_score: "सफलता की दर",
    dash_revenue: "मंथली कमाई",
    dash_capital: "शुरुआती लागत",
    dash_prob: "सफलता की संभावना",
    dash_neural_input: "डेटा के स्रोत",
    dash_source_web: "गूगल ट्रेंड्स",
    dash_source_reddit: "सोशल फीडबैक",
    dash_empty_title: "शुरू करने के लिए तैयार",
    dash_empty_desc: "अपने एरिया के लिए आइडिया देखने के लिए बाईं ओर लोकेशन लिखें।",
    dash_limit_reached: "सीमा समाप्त",
    dash_limit_desc: "आपके प्लान की सर्च सीमा पूरी हो गई है।",
    dash_upgrade_now: "अभी अपग्रेड करें",
    dash_recent_searches: "हाल की सर्च",
    dash_history_desc: "आपकी सर्च हिस्ट्री",
    dash_refresh: "रिफ्रेश",
    dash_use_current_loc: "वर्तमान लोकेशन का उपयोग करें",
    // Roadmap
    road_return: "डैशबोर्ड पर वापस जाएं",
    road_implement_guide: "कार्यान्वयन गाइड",
    road_directive: "बिज़नेस प्लान",
    road_milestones: "ज़रूरी कदम",
    road_timeline: "समय",
    road_team: "ज़रूरी सामान",
    road_phase: "कदम",
    road_priority: "ज़्यादा ज़रूरी",
    road_action: "क्या करना है",
    road_readiness: "प्लान तैयार है",
    road_confirmed_desc: "आपका स्टेप-बाय-स्टेप प्लान तैयार है। आप अभी शुरू कर सकते हैं।",
    road_print: "PDF डाउनलोड करें",
    road_preparing: "प्लान तैयार हो रहा है",
    road_analyzing: "मार्केट समझा जा रहा है...",
    road_strategy: "रणनीति",
    road_plan_title: "आपका ग्रोथ प्लान",
    road_success_conf: "एनालिसिस पूरा हुआ। सफलता की अच्छी संभावना है!",
    road_fast_growth: "तेज़ ग्रोथ",
    road_fast_desc: "कस्टमर्स को जल्दी ढूँढने और बिज़नेस बढ़ाने के लिए AI का उपयोग करें।",
    road_market_safety: "मार्केट सुरक्षा",
    road_safety_desc: "बदलावों के दौरान सुरक्षित रहने के लिए डेटा का सहारा लें।",
    road_6_months: "6 महीने का प्लान",
    road_taskforce: "ज़रूरी टूल्स",
    road_expert_exec: "काम के टिप्स",
    road_tip_1: "ज़रूरी काम ऑटोमेट करें",
    road_tip_2: "लोकल पहचान बनाएं",
    road_tip_3: "जल्दी शुरुआत करें",
    road_strategies: "ग्रोथ की रणनीतियां",
    road_loading_strat: "प्लान लोड हो रहा है...",
    // Profile
    prof_header: "प्रोफ़ाइल सेटिंग्स",
    prof_email_label: "ईमेल",
    prof_name: "पूरा नाम",
    prof_bio: "छोटा परिचय",
    prof_phone: "फोन नंबर",
    prof_company: "कंपनी",
    prof_company_name: "कंपनी का नाम",
    prof_location: "लोकेशन",
    prof_location_found: "लोकेशन मिल गई",
    prof_deploy_location: "इसी लोकेशन का उपयोग करें",
    prof_website: "वेबसाइट",
    prof_industry: "इंडस्ट्री",
    prof_save: "बदलाव सेव करें",
    prof_saving: "सेव किया जा रहा है...",
    prof_updated: "प्रोफ़ाइल सेव हो गई!",
    prof_placeholder_name: "पूरा नाम लिखें",
    prof_placeholder_bio: "अपने लक्ष्यों के बारे में बताएं...",
    prof_placeholder_phone: "फोन नंबर लिखें",
    prof_placeholder_company: "बिज़नेस का नाम",
    prof_placeholder_location: "शहर, देश",
    prof_placeholder_website: "https://example.com",
    prof_placeholder_industry: "अपनी इंडस्ट्री चुनें",
    prof_loading: "प्रोफ़ाइल लोड हो रही है...",
    // Pricing
    price_title: "प्राइसिंग प्लान",
    price_subtitle: "अपने लिए सबसे अच्छा प्लान चुनें और आगे बढ़ें।",
    price_explorer: "एक्सप्लोरर (फ्री)",
    price_explorer_desc: "बिज़नेस आइडिया ढूँढने की पहली सीढ़ी।",
    price_starter: "स्टार्टर",
    price_starter_desc: "गंभीर शुरुआत के लिए शानदार टूल्स।",
    price_pro: "प्रोफेशनल (प्रो)",
    price_pro_desc: "सफल उद्यमियों की पहली पसंद।",
    price_growth: "ग्रोथ बिज़नेस",
    price_growth_desc: "बढ़ते व्यापार के लिए सटीक एनालिसिस।",
    price_enterprise: "एंटरप्राइज़",
    price_enterprise_desc: "बड़ी एजेंसियों और कंपनियों के लिए।",
    price_feat_heatmap: "कम्पटीशन हीटमैप",
    price_feat_custom_search: "कस्टम AI सर्च",
    price_feat_review_score: "रिव्यू स्कोरिंग",
    price_feat_prediction: "ट्रेंड प्रेडिक्शन",
    price_feat_segment: "कस्टमर सेग्मेंटेशन",
    price_feat_forecast: "कमाई का पूर्वानुमान",
    price_feat_team: "टीम एक्सेस (2-5 यूजर)",
    price_feat_crm: "CRM इंटीग्रेशन",
    price_feat_white_label: "वाइट-लेबल समाधान",
    price_feat_api_lite: "लिमिटेड API",
    price_feat_api_full: "फुल API एक्सेस",
    price_monthly: "मासिक",
    price_yearly: "सालाना",
    price_annually: "वार्षिक",
    price_bill_monthly: "मासिक बिलिंग",
    price_bill_yearly: "वार्षिक बिलिंग",
    price_bill_annually: "वार्षिक भुगतान",
    price_most_popular: "लोकप्रिय",
    price_save: "20% की बचत",
    price_custom: "कस्टम प्लान",
    price_contact: "सम्पर्क करें",
    price_upgrade: "अपग्रेड करें",
    price_free: "फ्री शुरू करें",
    price_feat_support: "प्रायरिटी सपोर्ट",
    price_feat_api: "API एक्सेस",
    price_feat_multi: "मल्टी-एरिया",
    price_stat_capital: "कुल निवेश",
    price_stat_market: "मार्केट पकड़",
    price_stat_precision: "भरोसेमंद",
    price_trusted: "कई लोगों का भरोसा",
    price_partnerships: "सफल प्रोजेक्ट्स",
    dash_mentors: "मिलते-जुले बिज़नेस",
    dash_mentor_desc: "बेहतर जानकारी के लिए इस सेक्टर के बाकि बिज़नेस को देखें।",
    dash_connect: "एनालिसिस करें",
    // Footer & Generic
    foot_desc: "स्मार्ट बिज़नेस इंटेलिजेंस। AI के साथ बेहतर बिज़नेस बनाने में आपकी मदद करता है।",
    foot_status: "सिस्टम: सब ठीक है",
    foot_strategic: "एक्सप्लोर करें",
    foot_legal: "लीगल",
    foot_scan: "मार्केट सर्च",
    foot_regional: "लोकल जानकारी",
    foot_privacy: "प्राइवेसी",
    foot_terms: "नियम",
    foot_compliance: "अनुपालन",
    foot_contact: "सम्पर्क करें",
    foot_all_rights: "सर्वाधिकार सुरक्षित",
    foot_stable: "सिंगुलैरिटी v6.4.2",
    go_back: "वापस जाएं",
    // Auth
    auth_welcome: "साइन इन",
    auth_join: "अकाउंट बनाएं",
    auth_login_desc: "लॉगिन करें और अपना प्लान देखें।",
    auth_signup_desc: "नए आइडिया के लिए साइन अप करें।",
    auth_signin_tab: "साइन इन",
    auth_signup_tab: "साइन अप",
    auth_name: "पूरा नाम",
    auth_email: "ईमेल",
    auth_pass: "पासवर्ड",
    auth_confirm: "पासवर्ड कन्फर्म करें",
    auth_btn_login: "साइन इन करें",
    auth_btn_signup: "अकाउंट बनाएं",
    auth_or: "या इसके साथ",
    auth_google: "गूगल के साथ",
    auth_footer_1: "आज ही शुरुआत करें।",
    auth_footer_desc: "हमारा AI आपके लिए आइडिया ढूँढता है।",
    auth_feat_1: "स्मार्ट एनालिसिस",
    auth_feat_2: "कंपटीशन देखें",
    auth_feat_3: "मार्केट अलर्ट",
    auth_feat_4: "बिज़नेस रिपोर्ट",
    auth_init: "शुरू हो रहा है...",
    // Contact
    contact_title: "मदद और सपोर्ट",
    contact_subtitle: "कोई सवाल है? हमारी टीम आपकी मदद के लिए तैयार है।",
    contact_mail_title: "ईमेल करें",
    contact_mail_sub: "जवाब का समय: 2 घंटे",
    contact_loc_title: "हमारा ऑफिस",
    contact_loc_sub: "सिलिकॉन वैली, US",
    contact_support_title: "लाइव सपोर्ट",
    contact_support_sub: "प्रो यूजर्स के लिए उपलब्ध",
    contact_form_name: "आपका नाम",
    contact_form_email: "आपका ईमेल",
    contact_form_subject: "विषय",
    contact_form_message: "संदेश",
    contact_form_btn: "संदेश भेजें",
    contact_success: "धन्यवाद! हम जल्दी आपसे जुड़ेंगे।",
    contact_id_self: "अपना नाम लिखें...",
    contact_obj: "आपको क्या चाहिए?",
    contact_msg_dir: "आपका संदेश...",
    contact_transmit: "अभी भेजें",
    // Privacy, Terms, Compliance
    priv_title: "प्राइवेसी पॉलिसी",
    priv_section_1: "1. जानकारी जो हम इकट्ठा करते हैं",
    priv_content_1: "हम वह जानकारी इकट्ठा करते हैं जो आप हमें सीधे देते हैं, जैसे जब आप अकाउंट बनाते हैं या हमारी सेवाओं का उपयोग करते हैं।",
    priv_section_2: "2. जानकारी का उपयोग",
    priv_content_2: "हम जानकारी का उपयोग अपनी सेवाओं को बेहतर बनाने और आपसे बात करने के लिए करते हैं।",
    priv_section_3: "3. जानकारी साझा करना",
    priv_content_3: "हम आपकी अनुमति के बिना आपकी निजी जानकारी किसी और को नहीं बेचते।",
    priv_section_4: "4. डेटा सुरक्षा",
    priv_content_4: "हम आपकी जानकारी को सुरक्षित रखने के लिए कड़े सुरक्षा उपाय करते हैं।",
    priv_section_5: "5. हमसे सम्पर्क करें",
    priv_content_5: "यदि आपके कोई सवाल हैं, तो कृपया हमसे यहाँ सम्पर्क करें:",
    terms_title: "सेवा की शर्तें",
    terms_section_1: "1. शर्तों को स्वीकार करना",
    terms_content_1: "StarterScope का उपयोग करके, आप हमारी सभी शर्तों और कानूनों का पालन करने के लिए सहमत होते हैं।",
    terms_section_2: "2. यूजर अकाउंट",
    terms_content_2: "आप अपने अकाउंट को सुरक्षित रखने के लिए खुद ज़िम्मेदार हैं।",
    terms_section_3: "3. सेवाओं का उपयोग",
    terms_content_3: "हमारी सेवा बिज़नेस एनालिसिस के लिए है। इसका उपयोग गलत कामों के लिए न करें।",
    terms_section_4: "4. पेमेंट",
    terms_content_4: "सभी पेमेंट सुरक्षित तरीके से किए जाते हैं। सब्सक्रिप्शन कभी भी रद्द किया जा सकता है।",
    terms_section_5: "5. बदलाव",
    terms_content_5: "हम इन शर्तों को कभी भी बदल सकते हैं।",
    comp_title: "अनुपालन और सुरक्षा",
    comp_subtitle: "हम आपके डेटा को सुरक्षित रखने के लिए सभी वैश्विक नियमों का पालन करते हैं।",
    comp_section_1: "डेटा सुरक्षा",
    comp_content_1: "हम आपके डेटा के अधिकारों का पूरा सम्मान करते हैं और नियमों का पालन करते हैं।",
    comp_section_2: "सुरक्षित पेमेंट",
    comp_content_2: "सभी ट्रांजेक्शन सुरक्षित और एन्क्रिप्टेड होते हैं।",
    comp_section_3: "सिस्टम उपलब्धता",
    comp_content_3: "हमारा सिस्टम 24/7 काम करता है ताकि आपको कोई परेशानी न हो।",
    comp_section_4: "सुरक्षा लॉग",
    comp_content_4: "हम सभी गतिविधियों पर नज़र रखते हैं ताकि कोई गलत एक्सेस न हो सके।"
  },
  Spanish: {
    // Shared keys
    nav_dashboard: "Panel",
    nav_profile: "Mi Perfil",
    nav_login: "Iniciar Sesión",
    nav_logout: "Cerrar Sesión",
    nav_select_lang: "Idioma",
    nav_home: "Inicio",
    nav_theme_light: "Claro",
    nav_theme_dark: "Oscuro",
    nav_pricing: "Precios",
    nav_get_started: "Empezar",
    nav_online: "En línea",
    nav_current_plan: "Plan Actual",
    nav_upgrade_btn: "Mejorar",
    nav_manage_account: "Gestionar Cuenta",
    nav_analytics_view: "Vista Analítica",
    nav_view_tiers: "Ver Planes",
    nav_secure_signout: "Cerrar Sesión",
    nav_sync_active: "Sincronización Activa",
    // Home Page
    hero_badge: "IA PARA NEGOCIOS",
    hero_title_1: "Planifica tu",
    hero_title_2: "Éxito",
    hero_subtitle: "Halla las mejores ideas en tu ciudad con datos reales e IA.",
    btn_start_scan: "Buscar Ideas",
    btn_pricing: "Ver Planes",
    home_nav_features: "Cómo Funciona",
    home_nav_plan: "Plan",
    home_nav_stories: "Historias",
    home_feat_badge: "TOOLS SMART",
    home_feat_title_1: "Herramientas",
    home_feat_title_2: "de Éxito",
    home_story_badge: "HISTORIAS",
    home_story_revenue_label: "Mes",
    feat_title: "Cómo Funciona",
    feat_subtitle: "Analizamos qué falta en tu zona para que tú lo crees.",
    feat_1_title: "Elige Lugar",
    feat_2_title: "Mira el Profit",
    feat_3_title: "Guía Paso a Paso",
    banner_title: "Empieza hoy",
    banner_btn: "Empezar",
    dash_market_scope: "Buscar Lugar",
    dash_analyze: "Buscar",
    dash_ai_insights: "Informe de IA",
    dash_vector_global: "Tendencias",
    dash_vector_predict: "Ganancias",
    dash_results_header: "Resultados:",
    dash_strategic_opps: "Ideas",
    dash_view_plan: "Ver Plan",
    dash_match_score: "Éxito",
    dash_revenue: "Ingresos",
    dash_capital: "Inversión",
    dash_prob: "Probabilidad",
    dash_neural_input: "Datos",
    dash_empty_title: "Listo",
    dash_empty_desc: "Busca un lugar para ver ideas.",
    dash_limit_reached: "Límite",
    dash_upgrade_now: "Mejorar Plan",
    road_return: "Panel",
    road_milestones: "Pasos",
    road_timeline: "Tiempo",
    road_team: "Necesitas",
    road_phase: "PASO",
    road_confirmed_desc: "Ya puedes empezar.",
    road_strategy: "Estrategia",
    road_plan_title: "Tu Plan de Crecimiento",
    road_success_conf: "Listo para el éxito.",
    road_6_months: "6 Meses",
    prof_header: "Ajustes",
    prof_email_label: "Email",
    prof_name: "Nombre",
    prof_save: "Guardar",
    prof_saving: "Guardando...",
    prof_updated: "¡Guardado!",
    price_title: "Planes",
    price_subtitle: "Elige tu camino al éxito.",
    price_starter: "Inicia",
    price_pro: "Experto",
    price_free: "Gratis",
    price_upgrade: "Mejorar Ahora",
    price_stat_capital: "Capital",
    price_stat_market: "Precisión",
    price_stat_precision: "Confianza",
    foot_desc: "Negocios inteligentes con IA.",
    foot_status: "Sistemas: OK",
    foot_strategic: "Explora",
    foot_legal: "Legal",
    foot_scan: "Búsqueda",
    foot_regional: "Local",
    foot_privacy: "Privacidad",
    foot_terms: "Términos",
    foot_compliance: "Cumplimiento",
    foot_contact: "Contacto",
    foot_all_rights: "Reservados",
    foot_stable: "Singularity v6.4.2",
    go_back: "Volver",
    auth_welcome: "Entrar",
    auth_join: "Crea Cuenta",
    auth_btn_login: "Login",
    auth_btn_signup: "Crear",
    auth_or: "o con",
    auth_google: "Google",
    contact_title: "Ayuda",
    contact_subtitle: "Estamos aquí para ti 24/7.",
    contact_mail_title: "Email",
    contact_loc_title: "Sede",
    contact_support_title: "Soporte",
    contact_form_btn: "Enviar",
    contact_success: "¡Gracias!",
    contact_transmit: "Enviar",
    priv_title: "Privacidad",
    priv_section_1: "1. Datos",
    priv_content_1: "Recogemos los datos que nos das al crear tu cuenta.",
    priv_section_2: "2. Uso",
    priv_content_2: "Usamos los datos para mejorar el servicio.",
    priv_section_3: "3. Compartir",
    priv_content_3: "No vendemos tus datos a terceros.",
    priv_section_4: "4. Seguridad",
    priv_content_4: "Protegemos tu información con medidas de seguridad.",
    priv_section_5: "5. Contacto",
    priv_content_5: "Escríbenos a:",
    terms_title: "Términos",
    terms_section_1: "1. Aceptación",
    terms_content_1: "Al usar StarterScope aceptas nuestras condiciones.",
    terms_section_2: "2. Cuentas",
    terms_content_2: "Eres responsable de la seguridad de tu cuenta.",
    terms_section_3: "3. Servicio",
    terms_content_3: "Uso solo para análisis de negocios.",
    terms_section_4: "4. Pagos",
    terms_content_4: "Pagos seguros. Cancela cuando quieras.",
    terms_section_5: "5. Cambios",
    terms_content_5: "Podemos actualizar estos términos.",
    comp_title: "Seguridad y Cumplimiento",
    comp_subtitle: "Seguimos estándares globales.",
    comp_section_1: "Protección de Datos",
    comp_content_1: "Cumplimos con las leyes de privacidad.",
    comp_section_2: "Pagos Seguros",
    comp_content_2: "Transacciones cifradas.",
    comp_section_3: "Disponibilidad",
    comp_content_3: "Sistemas 24/7.",
    comp_section_4: "Registros",
    comp_content_4: "Monitoreo constante."
  },
  French: {
    // Shared keys
    nav_dashboard: "Tableau",
    nav_profile: "Profil",
    nav_login: "Connexion",
    nav_logout: "Déconnexion",
    nav_select_lang: "Langue",
    nav_home: "Accueil",
    nav_theme_light: "Clair",
    nav_theme_dark: "Sombre",
    nav_pricing: "Tarifs",
    nav_get_started: "Débuter",
    nav_online: "En ligne",
    nav_current_plan: "Plan Actuel",
    nav_upgrade_btn: "Améliorer",
    nav_manage_account: "Gérer Compte",
    nav_analytics_view: "Vue Analytique",
    nav_view_tiers: "Voir Plans",
    nav_secure_signout: "Déconnexion",
    nav_sync_active: "Sync Active",
    // Home Page
    hero_badge: "IA POUR BUSINESS",
    hero_title_1: "Plan de",
    hero_title_2: "Succès",
    hero_subtitle: "Trouvez les meilleures idées avec l'IA.",
    btn_start_scan: "Chercher",
    btn_pricing: "Plans",
    home_nav_features: "Comment ça marche",
    home_nav_plan: "Plan",
    home_nav_stories: "Succès",
    home_feat_badge: "OUTILS SMART",
    home_feat_title_1: "Outils de",
    home_feat_title_2: "Réussite",
    home_story_badge: "HISTOIRES",
    home_story_revenue_label: "Revenu",
    feat_title: "Comment ça marche",
    feat_subtitle: "Nous analysons le marché pour vous.",
    feat_1_title: "Lieu",
    feat_2_title: "Profit",
    feat_3_title: "Guide",
    banner_title: "Lancez-vous",
    banner_btn: "Débuter",
    dash_market_scope: "Lieu",
    dash_analyze: "Analyser",
    dash_ai_insights: "IA Rapport",
    dash_vector_global: "Tendances",
    dash_vector_predict: "Prévisions",
    dash_results_header: "Résultats :",
    dash_strategic_opps: "Idées",
    dash_view_plan: "Voir Plan",
    dash_match_score: "Succès",
    dash_revenue: "Revenu",
    dash_capital: "Investissement",
    dash_prob: "Probabilité",
    dash_neural_input: "Données",
    dash_empty_title: "Prêt",
    dash_empty_desc: "Cherchez un lieu.",
    dash_limit_reached: "Limite",
    dash_upgrade_now: "Améliorer",
    road_return: "Tableau",
    road_milestones: "Étapes",
    road_timeline: "Temps",
    road_team: "Besoins",
    road_phase: "ÉTAPE",
    road_confirmed_desc: "Lancez-vous !",
    road_strategy: "Stratégie",
    road_plan_title: "Plan de Croissance",
    road_success_conf: "Succès garanti.",
    road_6_months: "6 Mois",
    prof_header: "Profil",
    prof_email_label: "Email",
    prof_name: "Nom",
    prof_save: "Sauver",
    prof_saving: "Enregistrement...",
    prof_updated: "Enregistré !",
    price_title: "Tarifs",
    price_subtitle: "Votre chemin vers le succès.",
    price_starter: "Début",
    price_pro: "Pro",
    price_free: "Gratuit",
    price_upgrade: "Améliorer",
    price_stat_capital: "Capital",
    price_stat_market: "IA",
    price_stat_precision: "Fiabilité",
    foot_desc: "Intelligence d'affaires simple.",
    foot_status: "Statut: OK",
    foot_strategic: "Explorer",
    foot_legal: "Légal",
    foot_scan: "Recherche",
    foot_regional: "Local",
    foot_privacy: "Privé",
    foot_terms: "Conditions",
    foot_compliance: "Conformité",
    foot_contact: "Contact",
    foot_all_rights: "Réservés",
    foot_stable: "Singularity v6.4.2",
    go_back: "Retour",
    auth_welcome: "Entrer",
    auth_join: "Créer",
    auth_btn_login: "Login",
    auth_btn_signup: "Créer",
    auth_or: "ou via",
    auth_google: "Google",
    contact_title: "Aide",
    contact_subtitle: "On vous aide 24/24.",
    contact_mail_title: "Email",
    contact_loc_title: "Bureau",
    contact_support_title: "Support",
    contact_form_btn: "Envoyer",
    contact_success: "Merci !",
    contact_transmit: "Envoyer",
    priv_title: "Confidentialité",
    priv_section_1: "1. Données",
    priv_content_1: "Nous collectons vos données de compte.",
    priv_section_2: "2. Usage",
    priv_content_2: "Usage pour améliorer le service.",
    priv_section_3: "3. Partage",
    priv_content_3: "Pas de partage avec des tiers.",
    priv_section_4: "4. Sécurité",
    priv_content_4: "Données protégées.",
    priv_section_5: "5. Contact",
    priv_content_5: "Contactez-nous :",
    terms_title: "Conditions",
    terms_section_1: "1. Acceptation",
    terms_content_1: "En utilisant StarterScope vous acceptez nos termes.",
    terms_section_2: "2. Comptes",
    terms_content_2: "Vous êtes responsable de votre compte.",
    terms_section_3: "3. Service",
    terms_content_3: "Analyse business uniquement.",
    terms_section_4: "4. Paiements",
    terms_content_4: "Paiements sécurisés.",
    terms_section_5: "5. Changements",
    terms_content_5: "Termes modifiables.",
    comp_title: "Conformité",
    comp_subtitle: "Standards mondiaux.",
    comp_section_1: "Protection",
    comp_content_1: "Respect de la vie privée.",
    comp_section_2: "Paiements",
    comp_content_2: "Transactions cryptées.",
    comp_section_3: "Dispo",
    comp_content_3: "99.9% uptime.",
    comp_section_4: "Logs",
    comp_content_4: "Monitoring 24/7."
  },
  German: {
    // Shared keys
    nav_dashboard: "Dashboard",
    nav_profile: "Profil",
    nav_login: "Anmelden",
    nav_logout: "Abmelden",
    nav_select_lang: "Sprache",
    nav_home: "Home",
    nav_theme_light: "Hell",
    nav_theme_dark: "Dunkel",
    nav_pricing: "Preise",
    nav_get_started: "Starten",
    nav_online: "Online",
    nav_current_plan: "Aktueller Plan",
    nav_upgrade_btn: "Upgrade",
    nav_manage_account: "Konto verwalten",
    nav_analytics_view: "Analyse",
    nav_view_tiers: "Preise ansehen",
    nav_secure_signout: "Abmelden",
    nav_sync_active: "Sync Aktiv",
    // Home Page
    hero_badge: "KI FÜR GRÜNDER",
    hero_title_1: "Dein",
    hero_title_2: "Erfolgsplan",
    hero_subtitle: "Finde Ideen mit echten Daten und KI.",
    btn_start_scan: "Suchen",
    btn_pricing: "Preise",
    home_nav_features: "So geht's",
    home_nav_plan: "Plan",
    home_nav_stories: "Erfolge",
    home_feat_badge: "TOOLS",
    home_feat_title_1: "Tools für",
    home_feat_title_2: "Erfolg",
    home_story_badge: "ERFOLGE",
    home_story_revenue_label: "Umsatz",
    feat_title: "So geht's",
    feat_subtitle: "Wir finden Lücken für Dich.",
    feat_1_title: "Ort",
    feat_2_title: "Gewinn",
    feat_3_title: "Guide",
    banner_title: "Starte jetzt",
    banner_btn: "Starten",
    dash_market_scope: "Ort",
    dash_analyze: "Analyse",
    dash_ai_insights: "KI-Bericht",
    dash_vector_global: "Trends",
    dash_vector_predict: "Gewinn",
    dash_results_header: "Ergebnisse:",
    dash_strategic_opps: "Ideen",
    dash_view_plan: "Plan sehen",
    dash_match_score: "Erfolg",
    dash_revenue: "Umsatz",
    dash_capital: "Kapital",
    dash_prob: "Chance",
    dash_neural_input: "Daten",
    dash_empty_title: "Bereit",
    dash_empty_desc: "Ort eingeben.",
    dash_limit_reached: "Limit",
    dash_upgrade_now: "Upgraden",
    road_return: "Dashboard",
    road_milestones: "Schritte",
    road_timeline: "Zeit",
    road_team: "Bedarf",
    road_phase: "SCHRITT",
    road_confirmed_desc: "Leg los!",
    road_strategy: "Strategie",
    road_plan_title: "Dein Plan",
    road_success_conf: "Auf geht's!",
    road_6_months: "6 Monate",
    prof_header: "Profil",
    prof_email_label: "E-Mail",
    prof_name: "Name",
    prof_save: "Sichern",
    prof_updated: "Gespeichert!",
    price_title: "Preise",
    price_subtitle: "Dein Weg zum Erfolg.",
    price_starter: "Start",
    price_pro: "Pro",
    price_free: "Gratis",
    price_upgrade: "Upgrade Jetzt",
    price_stat_capital: "Kapital",
    price_stat_market: "KI",
    price_stat_precision: "Verlässlich",
    foot_desc: "Einfache Business Intelligence.",
    foot_status: "Status: OK",
    foot_strategic: "Entdecken",
    foot_legal: "Recht",
    foot_scan: "Suche",
    foot_regional: "Lokal",
    foot_privacy: "Daten",
    foot_terms: "AGB",
    foot_compliance: "Compliance",
    foot_contact: "Kontakt",
    foot_all_rights: "Rechte",
    foot_stable: "Singularity v6.4.2",
    go_back: "Zurück",
    auth_welcome: "Anmelden",
    auth_join: "Konto",
    auth_btn_login: "Anmelden",
    auth_btn_signup: "Erstellen",
    auth_or: "oder mit",
    auth_google: "Google",
    contact_title: "Hilfe",
    contact_subtitle: "Wir sind 24/7 da.",
    contact_mail_title: "E-Mail",
    contact_loc_title: "Standort",
    contact_support_title: "Support",
    contact_form_btn: "Senden",
    contact_success: "Danke!",
    contact_transmit: "Senden",
    priv_title: "Datenschutz",
    priv_section_1: "1. Daten",
    priv_content_1: "Wir sammeln Daten bei Kontoerstellung.",
    priv_section_2: "2. Nutzung",
    priv_content_2: "Nutzung zur Verbesserung.",
    priv_section_3: "3. Weitergabe",
    priv_content_3: "Keine Weitergabe an Dritte.",
    priv_section_4: "4. Sicherheit",
    priv_content_4: "Deine Daten sind sicher.",
    priv_section_5: "5. Kontakt",
    priv_content_5: "Kontaktiere uns:",
    terms_title: "AGB",
    terms_section_1: "1. Annahme",
    terms_content_1: "Mit StarterScope akzeptierst Du unsere AGB.",
    terms_section_2: "2. Konten",
    terms_content_2: "Du bist für Dein Konto verantwortlich.",
    terms_section_3: "3. Service",
    terms_content_3: "Nur für Business-Analyse.",
    terms_section_4: "4. Zahlung",
    terms_content_4: "Sichere Zahlung. Jederzeit kündbar.",
    terms_section_5: "5. Änderungen",
    terms_content_5: "AGB können sich ändern.",
    comp_title: "Sicherheit",
    comp_subtitle: "Globale Standards.",
    comp_section_1: "Schutz",
    comp_content_1: "Datenschutz nach Gesetz.",
    comp_section_2: "Zahlung",
    comp_content_2: "Verschlüsselt.",
    comp_section_3: "Verfügbar",
    comp_content_3: "99.9% online.",
    comp_section_4: "Logs",
    comp_content_4: "Überwachung 24/7."
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("English");

  // Load language from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem("app_lang");
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  // Save language to localStorage on change
  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
