services:
  - type: web
    name: trendai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    port: 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        sync: false
      - key: POLLINATION_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DODO_PAYMENTS_API_KEY
        sync: false
      - key: DODO_WEBHOOK_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false